/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actividad2SMTP;

import jakarta.mail.AuthenticationFailedException;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Multipart;
import jakarta.mail.NoSuchProviderException;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.AddressException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author manana
 */
public class VistaMain extends javax.swing.JFrame {

    /**
     * Creates new form VistaMain
     */
    final Properties prop = new Properties();
    Session mailSession;
    Transport transportValidation = null;
    String usuario = "";
    String clave = "";
    String servidor = "";
    String puerto = "";
    ArrayList<File> file = new ArrayList<>();
    int numFile = 0;

    public VistaMain() {
        initComponents();
        setLocationRelativeTo(null);
        jBAdArchivo.setEnabled(false);
        jBEnviar.setEnabled(false);
        jBDesconectar.setEnabled(false);
        jTRemitente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTServidorSMPT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTPuerto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTClave = new javax.swing.JTextField();
        jRadioButtonSin = new javax.swing.JRadioButton();
        jRadioButtonCon = new javax.swing.JRadioButton();
        jBConectar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTRemitente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTDestinatario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTAsunto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensaje = new javax.swing.JTextArea();
        jBEnviar = new javax.swing.JButton();
        jTArchivo = new javax.swing.JTextField();
        jBAdArchivo = new javax.swing.JButton();
        jBDesconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Servidor SMTP:");

        jTServidorSMPT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTServidorSMPT.setForeground(new java.awt.Color(51, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Usuario:");

        jTUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTUsuario.setForeground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Puerto:");

        jTPuerto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTPuerto.setForeground(new java.awt.Color(51, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Clave:");

        jTClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTClave.setForeground(new java.awt.Color(51, 153, 255));

        buttonGroup1.add(jRadioButtonSin);
        jRadioButtonSin.setText("Sin TLS");

        buttonGroup1.add(jRadioButtonCon);
        jRadioButtonCon.setText("Con TLS");

        jBConectar.setText("Conectar");
        jBConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Remitente:");

        jTRemitente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTRemitente.setForeground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Destinatario:");

        jTDestinatario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTDestinatario.setForeground(new java.awt.Color(51, 153, 255));

        jLabel7.setText("Asunto:");

        jTAsunto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTAsunto.setForeground(new java.awt.Color(51, 153, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Redacta el cuerpo del mensaje:");

        jTextAreaMensaje.setColumns(20);
        jTextAreaMensaje.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensaje);

        jBEnviar.setText("Enviar Mensaje");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jBAdArchivo.setText("ADJUNTAR ARCHIVO");
        jBAdArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdArchivoActionPerformed(evt);
            }
        });

        jBDesconectar.setText("DESCONECTAR");
        jBDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(94, 94, 94)
                                .addComponent(jTArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAdArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTAsunto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTServidorSMPT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSin)
                                .addGap(31, 31, 31)
                                .addComponent(jRadioButtonCon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTClave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBDesconectar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTDestinatario))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jBEnviar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTServidorSMPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSin)
                    .addComponent(jRadioButtonCon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConectar)
                    .addComponent(jBDesconectar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTRemitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAdArchivo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarActionPerformed

        if (jTServidorSMPT.getText().equalsIgnoreCase("") || jTPuerto.getText().equalsIgnoreCase("") || jTUsuario.getText().equalsIgnoreCase("") || jTClave.getText().equalsIgnoreCase("") || (jRadioButtonCon.isSelected() == false && jRadioButtonSin.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "CREDENCIALES INCOMPLETAS", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                usuario = jTUsuario.getText();
                clave = jTClave.getText();
                servidor = jTServidorSMPT.getText();
                puerto = jTPuerto.getText();

                prop.put("mail.smtp.username", usuario);
                prop.put("mail.smtp.password", clave);
                prop.put("mail.smtp.host", servidor);
                prop.put("mail.smtp.port", puerto);
                prop.put("mail.smtp.auth", "true");
                prop.put("mail.debug", "true");
                prop.put("mail.smtp.starttls.enable", jRadioButtonCon.isSelected()); 
               

                // Create the Session with the user credentials
                mailSession = Session.getInstance(prop, new jakarta.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(prop.getProperty("mail.smtp.username"),
                                prop.getProperty("mail.smtp.password"));
                    }

                });

                transportValidation = mailSession.getTransport();
                transportValidation.connect();

                JOptionPane.showMessageDialog(this, "CONECTADO AL SERVIDOR");
                jBEnviar.setEnabled(true);
                jBAdArchivo.setEnabled(true);
                jBDesconectar.setEnabled(true);
                jBConectar.setEnabled(false);
                jTRemitente.setText(jTUsuario.getText());
            } catch (AuthenticationFailedException ex) {
                Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "CREDENCIALES INCORRECTAS", "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (NoSuchProviderException ex) {
                Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "NO SE HA PODIDO CONECTAR CON EL SERVIDOR", "ERROR", JOptionPane.ERROR_MESSAGE);
            } catch (MessagingException ex) {
                Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "NO SE HA PODIDO CONECTAR CON EL SERVIDOR", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jBConectarActionPerformed

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed

        try {
            if (jTRemitente.getText().equalsIgnoreCase("") || jTDestinatario.getText().equalsIgnoreCase("")) {

                JOptionPane.showMessageDialog(this, "INTRODUCE UN REMITENTE Y DESTINATARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                if (jTextAreaMensaje.getText().equalsIgnoreCase("") && jTArchivo.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(this, "INTRODUCE UN MENSAJE O ARCHIVO PARA ENVIAR", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (!jTAsunto.getText().equals("")) {
                        Message message = new MimeMessage(mailSession);
                        // Set From and subject email properties
                        message.setFrom(new InternetAddress(usuario));
                        message.setSubject(jTAsunto.getText());

                        // Set to, cc & bcc recipients
                        InternetAddress[] toEmailAddresses
                                = InternetAddress.parse(jTDestinatario.getText());

                        message.setRecipients(Message.RecipientType.TO, toEmailAddresses);

                        Multipart multipart = new MimeMultipart();

                        // create the 1st message body part
                        MimeBodyPart messageBodyPart = new MimeBodyPart();
                        // Add a plain message (HTML can also be added with setContent)
                        if (jTextAreaMensaje.getText().equalsIgnoreCase("")) {
                            messageBodyPart.setText("SIN MENSAJE");
                        } else {
                            messageBodyPart.setText(jTextAreaMensaje.getText());
                        }

                        // Add the BodyPart to the Multipart object
                        multipart.addBodyPart(messageBodyPart);

                        for (int i = 0; i < file.size(); i++) {
                            // 2nd. bodyPart with an attached file
                            messageBodyPart = new MimeBodyPart();
                            messageBodyPart.attachFile(file.get(i));
                            // Add the BodyPart to the Multipart object
                            multipart.addBodyPart(messageBodyPart);
                        }

                        // Add the multipart object to the message
                        message.setContent(multipart);

                        Transport.send(message);

                        vaciarCampos();

                        JOptionPane.showMessageDialog(this, "MENSAJE ENVIADO");
                    } else {
                        JOptionPane.showMessageDialog(this, "INTRODUCE UN ASUNTO", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        } catch (AddressException ex) {
            Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBAdArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String selectedFilePath = fileChooser.getSelectedFile().getPath();
            jTArchivo.setText(selectedFilePath);
            if (file.size() > 0) {
                jTArchivo.setText("Mas de 1 Arhivo Adjunto....");
            }
            File fChoser = fileChooser.getSelectedFile();
            file.add(fChoser);

        } else {
            System.out.println("No file selected.");
        }
    }//GEN-LAST:event_jBAdArchivoActionPerformed

    private void jBDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesconectarActionPerformed
        
        try {
            transportValidation.close();
            transportValidation = null;
            
            vaciarCampos();
            jTServidorSMPT.setText("");
            jTPuerto.setText("");
            jTUsuario.setText("");
            jTClave.setText("");
            
            jBEnviar.setEnabled(false);
            jBAdArchivo.setEnabled(false);
            jBConectar.setEnabled(true);
            jBDesconectar.setEnabled(false);
        } catch (MessagingException ex) {
            Logger.getLogger(VistaMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBDesconectarActionPerformed

    private void vaciarCampos() {

        jTRemitente.setText("");
        jTDestinatario.setText("");
        jTArchivo.setText("");
        jTextAreaMensaje.setText("");
        jTAsunto.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMain().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAdArchivo;
    private javax.swing.JButton jBConectar;
    private javax.swing.JButton jBDesconectar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonCon;
    private javax.swing.JRadioButton jRadioButtonSin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTArchivo;
    private javax.swing.JTextField jTAsunto;
    private javax.swing.JTextField jTClave;
    private javax.swing.JTextField jTDestinatario;
    private javax.swing.JTextField jTPuerto;
    private javax.swing.JTextField jTRemitente;
    private javax.swing.JTextField jTServidorSMPT;
    private javax.swing.JTextField jTUsuario;
    private javax.swing.JTextArea jTextAreaMensaje;
    // End of variables declaration//GEN-END:variables

}
